[general]
import = ["~/.config/alacritty/themes/themes/aura.toml"]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.8
blur = true

[font]
normal = { family = "Hack", style = "Regular" }
size = 20
